version: '3.7'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www/

  nginx:
    image: nginx:alpine
    depends_on:
      - php
    volumes:
      - ./public:/var/www/public:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 4242:80
