version: '3.7'

services:
  app:
    container_name: app
    build:
      dockerfile: ./docker/Dockerfile
      target: dev
      context: .
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/php/php-development.ini:/usr/local/etc/php/php.ini
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/supervisord/supervisord.conf:/etc/supervisor/supervisord.conf
