index:
    path: /
    controller: KaamelottGifboard\Action\Gif\Index

# XHR

count_quotes:
    path: /xhr/count_quotes
    controller: KaamelottGifboard\Action\Xhr\CountQuotes

get_characters:
    path: /xhr/get_characters
    controller: KaamelottGifboard\Action\Xhr\GetCharacters
    defaults: { name: '' }

# Gifs

get_by_slug:
    path: /gif/{slug}
    controller: KaamelottGifboard\Action\Gif\Slug
    defaults: { slug: '' }

get_by_code:
    path: /g/{code}
    controller: KaamelottGifboard\Action\Gif\Code
    requirements:
        shortUrl: '[a-z0-9]+'

get_by_character:
    path: /search/character/{name}
    controller: KaamelottGifboard\Action\Gif\Character
    defaults: { name: '' }

get_random:
    path: /random
    controller: KaamelottGifboard\Action\Gif\Random

# Search

search_quote:
    path: /search/quote
    controller: KaamelottGifboard\Action\Search\Quote
    defaults: { quote: '' }

# Sitemap

sitemap:
    path: /sitemap.xml
    controller: KaamelottGifboard\Action\Sitemap\Index
    defaults:
        _format: xml

# Images

quote_image:
    path: /gifs/{filename}
    defaults:
        _format: gif

character_image:
    path: /characters/{filename}
    defaults:
        _format: png
