search_index:
    path: /
    controller: KaamelottGifboard\Action\Search\Gif::getAll

search_count:
    path: /search/gif/count
    controller: KaamelottGifboard\Action\Search\Gif::countAll

search_character:
    path: /search/character/{name}
    controller: KaamelottGifboard\Action\Search\Gif::byCharacter
    defaults: { name: '' }

search_quote:
    path: /search/quote
    controller: KaamelottGifboard\Action\Search\Quote
    defaults: { quote: '' }

get_characters:
    path: /search/characters
    controller: KaamelottGifboard\Action\Search\Character
    defaults: { name: '' }
