controllers:
    resource:
        path: ../src/Action/
        namespace: KaamelottGifboard\Action
    type: attribute
    host: "%host_name%"

get_by_code_short:
    path: /g/{code}
    controller: KaamelottGifboard\Action\Gif\Code
    requirements:
        shortUrl: '[a-z0-9]+'
    host: "%short_host_name%"

quote_image:
    path: /gifs/{filename}
    defaults:
        _format: gif

character_image:
    path: /characters/{filename}
    defaults:
        _format: jpg
