parameters:
    gifs_json_path: '%kernel.project_dir%/gifs.json'
    public_path: '%kernel.project_dir%/public'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $gifsJsonFile: '%gifs_json_path%'
            string $publicPath: '%public_path%'

    KaamelottGifboard\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    KaamelottGifboard\Action\:
        resource: '../src/Action'
        tags: [ 'controller.service_arguments' ]
