parameters:
    host_name: '%env(HOST_NAME)%'
    short_host_name: '%env(SHORT_HOST_NAME)%'
    gifs_json_path: '%kernel.project_dir%/gifs.json'
    redirection_json_path: '%kernel.project_dir%/redirection.json'
    public_path: '%kernel.project_dir%/public'
    twitter_api_key: '%env(TWITTER_API_KEY)%'
    twitter_api_key_secret: '%env(TWITTER_API_KEY_SECRET)%'
    twitter_access_token: '%env(TWITTER_ACCESS_TOKEN)%'
    twitter_access_token_secret: '%env(TWITTER_ACCESS_TOKEN_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $gifsJsonFile: '%gifs_json_path%'
            string $redirectionJsonFile: '%redirection_json_path%'
            string $publicPath: '%public_path%'
            string $twitterApiKey: '%twitter_api_key%'
            string $twitterApiKeySecret: '%twitter_api_key_secret%'
            string $twitterAccessToken: '%twitter_access_token%'
            string $twitterAccessTokenSecret: '%twitter_access_token_secret%'

    KaamelottGifboard\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'

    KaamelottGifboard\Action\:
        resource: '../src/Action'
        tags: [ 'controller.service_arguments' ]
