parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $gifsJsonFile: '%kernel.project_dir%/gifs.json'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Action\:
        resource: '../src/Action'
        tags: [ 'controller.service_arguments' ]
