parameters:
    gifs_json_path: '%kernel.project_dir%/gifs.json'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            string $gifsJsonFile: '%gifs_json_path%'

    KaamelottGifboard\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    KaamelottGifboard\Action\:
        resource: '../src/Action'
        tags: [ 'controller.service_arguments' ]
